# Generated by Django 5.1.3 on 2025-03-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facial", "0003_facial_is_ignore_alter_facial_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedFacial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "suggested_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("face_embeddings", models.TextField(null=True)),
                ("total_times", models.IntegerField(default=0)),
                ("distinct_days", models.IntegerField(default=0)),
                ("title", models.CharField(default="", max_length=256)),
                ("is_ignore", models.BooleanField(default=False)),
                ("is_almost", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        unique=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_face",
                        to="facial.facial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
