# Generated by Django 5.1.3 on 2025-12-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggested_facial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedfacial",
            name="confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="suggestedfacial",
            name="confidence_2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="suggestedfacial",
            name="confidence_3",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="suggestedfacial",
            name="face_embeddings_2",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="suggestedfacial",
            name="face_embeddings_3",
            field=models.TextField(null=True),
        ),
    ]
