# Generated by Django 5.1.3 on 2024-12-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoundingBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_type", models.CharField(max_length=256)),
                ("camera_id", models.CharField(max_length=256)),
                ("x1", models.IntegerField()),
                ("y1", models.IntegerField()),
                ("x2", models.IntegerField()),
                ("y2", models.IntegerField()),
            ],
        ),
    ]
