# Generated by Django 5.1.3 on 2025-01-21 17:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facial",
            name="processing",
            field=models.CharField(default="In processing", max_length=256),
        ),
    ]
