# Generated by Django 5.1.3 on 2025-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facial", "0002_facial_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="facial",
            name="is_ignore",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facial",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="facial",
            name="video_url",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="facial",
            name="avatar",
            field=models.TextField(blank=True, null=True, verbose_name="avatar"),
        ),
    ]
