# Generated by Django 5.1.3 on 2025-01-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlarmDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=256)),
                (
                    "identity_name",
                    models.CharField(default="", max_length=256, unique=True),
                ),
                ("hass_entry_id", models.CharField(default="", max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
