# Generated by Django 5.1.3 on 2025-12-26 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmdevice",
            name="volume",
            field=models.IntegerField(
                default=50, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
