# Generated by Django 5.1.3 on 2026-01-05 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0002_alarmdevice_volume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarmdevice",
            name="volume",
        ),
        migrations.AddField(
            model_name="alarmdevice",
            name="type",
            field=models.CharField(
                choices=[("OUTDOOR", "OUTDOOR Alarm"), ("INDOOR", "INDOOR Alarm")],
                default="INDOOR",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AlarmDeviceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mic_enabled", models.BooleanField(default=False)),
                (
                    "alarm_mode",
                    models.CharField(
                        choices=[("off", "Off"), ("night", "Night"), ("away", "Away")],
                        default="off",
                        max_length=32,
                    ),
                ),
                (
                    "volume",
                    models.IntegerField(
                        default=50,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unusual_sound_mode",
                    models.CharField(
                        choices=[("travel", "Travel"), ("alarm", "Alarm")],
                        default="alarm",
                        max_length=32,
                    ),
                ),
                (
                    "unusual_sound_mode_sound",
                    models.CharField(
                        choices=[
                            ("alarm", "Alarm"),
                            ("party", "Party"),
                            ("movie", "Movie"),
                            ("dog_barking", "Dog Barking"),
                        ],
                        default="alarm",
                        max_length=32,
                    ),
                ),
                (
                    "unusual_sound_duration_sound",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unusual_sound_led",
                    models.CharField(
                        choices=[
                            ("purple", "Purple"),
                            ("red", "Red"),
                            ("amber", "Amber"),
                        ],
                        default="red",
                        max_length=32,
                    ),
                ),
                (
                    "loiter_mode",
                    models.CharField(
                        choices=[("travel", "Travel"), ("alarm", "Alarm")],
                        default="alarm",
                        max_length=32,
                    ),
                ),
                (
                    "loiter_mode_sound",
                    models.CharField(
                        choices=[
                            ("alarm", "Alarm"),
                            ("party", "Party"),
                            ("movie", "Movie"),
                            ("dog_barking", "Dog Barking"),
                        ],
                        default="alarm",
                        max_length=32,
                    ),
                ),
                (
                    "loiter_duration_sound",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "loiter_led",
                    models.CharField(
                        choices=[
                            ("purple", "Purple"),
                            ("red", "Red"),
                            ("amber", "Amber"),
                        ],
                        default="red",
                        max_length=32,
                    ),
                ),
                (
                    "parcel_detect_mode",
                    models.CharField(
                        choices=[("travel", "Travel"), ("alarm", "Alarm")],
                        default="alarm",
                        max_length=32,
                    ),
                ),
                (
                    "parcel_detect_mode_sound",
                    models.CharField(
                        choices=[
                            ("alarm", "Alarm"),
                            ("party", "Party"),
                            ("movie", "Movie"),
                            ("dog_barking", "Dog Barking"),
                        ],
                        default="alarm",
                        max_length=32,
                    ),
                ),
                (
                    "parcel_detect_duration_sound",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "parcel_detect_led",
                    models.CharField(
                        choices=[
                            ("purple", "Purple"),
                            ("red", "Red"),
                            ("amber", "Amber"),
                        ],
                        default="red",
                        max_length=32,
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_device",
                        to="alarm.alarmdevice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
