# Generated by Django 5.1.3 on 2026-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0003_remove_alarmdevice_volume_alarmdevice_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmdevice",
            name="unusual_sound_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alarmdevice",
            name="voice_ai_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="alarmdeviceconfig",
            name="loiter_mode_sound",
            field=models.CharField(
                choices=[
                    ("alarm", "Alarm"),
                    ("people_home", "People at Home"),
                    ("running_appliances", "Running Appliances"),
                    ("barking_dogs", "Barking Dogs"),
                ],
                default="alarm",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="alarmdeviceconfig",
            name="parcel_detect_mode_sound",
            field=models.CharField(
                choices=[
                    ("alarm", "Alarm"),
                    ("people_home", "People at Home"),
                    ("running_appliances", "Running Appliances"),
                    ("barking_dogs", "Barking Dogs"),
                ],
                default="alarm",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="alarmdeviceconfig",
            name="unusual_sound_mode_sound",
            field=models.CharField(
                choices=[
                    ("alarm", "Alarm"),
                    ("people_home", "People at Home"),
                    ("running_appliances", "Running Appliances"),
                    ("barking_dogs", "Barking Dogs"),
                ],
                default="alarm",
                max_length=32,
            ),
        ),
    ]
