# Generated by Django 5.1.3 on 2026-01-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0004_alarmdevice_unusual_sound_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarmdevice",
            name="unusual_sound_enabled",
        ),
        migrations.RemoveField(
            model_name="alarmdevice",
            name="voice_ai_enabled",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="loiter_duration_sound",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="loiter_mode",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="loiter_mode_sound",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="parcel_detect_duration_sound",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="parcel_detect_mode",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="parcel_detect_mode_sound",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="unusual_sound_duration_sound",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="unusual_sound_mode",
        ),
        migrations.RemoveField(
            model_name="alarmdeviceconfig",
            name="unusual_sound_mode_sound",
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="audio_mode",
            field=models.CharField(
                choices=[("normal", "Normal"), ("immersive", "Immersive")],
                default="normal",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="microphone_sensitive",
            field=models.CharField(
                choices=[("medium", "Medium"), ("low", "Low"), ("High", "High")],
                default="High",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="occupancy_illusion",
            field=models.CharField(
                choices=[
                    ("off", ""),
                    ("people", "People"),
                    ("appliances", "Appliances"),
                    ("barking_dogs", "Dogs"),
                ],
                default="off",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="power_equalizer",
            field=models.CharField(
                choices=[("normal", "Normal"), ("low", "Low"), ("standby", "Standby")],
                default="standby",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="smart_announcement_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="unusual_sound_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="voice_ai_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmdeviceconfig",
            name="volume_equalizer",
            field=models.CharField(
                choices=[("flat", "Flat"), ("voice", "Voice"), ("bass", "Bass")],
                default="bass",
                max_length=16,
            ),
        ),
    ]
