# Generated by Django 5.1.3 on 2026-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0005_remove_alarmdevice_unusual_sound_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmdevice",
            name="version_fw",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
