# Generated by Django 5.1.3 on 2026-01-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mac_address", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("S1", "S1"), ("K11", "K11")],
                        default="S1",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
