# Generated by Django 5.1.3 on 2026-01-07 09:29

from django.db import migrations, transaction


def create_cloudflare_restart_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*/12",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    with transaction.atomic():
        PeriodicTask.objects.get_or_create(
            name="Hub | Auto restart Cloudflare token (12h)",
            task="hub_operations.tasks.hub_auto_restart_cloudflare_token",
            crontab=schedule,
            defaults={
                "enabled": True,
                "queue": "hub_operations_queue",
                "routing_key": "hub_operations.task",
                "description": "Auto refresh / restart Cloudflare token every 12 hours",
            },
        )


def reverse_cloudflare_restart_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    PeriodicTask.objects.filter(
        name="Hub | Auto restart Cloudflare token (12h)"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [("django_celery_beat", "0016_alter_crontabschedule_timezone")]

    operations = [
        migrations.RunPython(
            create_cloudflare_restart_task,
            reverse_cloudflare_restart_task,
        ),
    ]
