# Generated by Django 5.1.3 on 2024-12-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("username", models.CharField(max_length=256, null=True)),
                ("password", models.CharField(max_length=256, null=True)),
                ("ip", models.CharField(max_length=256, null=True)),
                ("ring_id", models.CharField(max_length=256, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("RTSP", "RTSP Camera"), ("RING", "Ring Camera")],
                        default="RTSP",
                        max_length=16,
                    ),
                ),
                (
                    "ring_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ring.ringaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RingCamera",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("camera.camera",),
        ),
        migrations.CreateModel(
            name="RTSPCamera",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("camera.camera",),
        ),
    ]
