# Generated by Django 5.1.3 on 2024-12-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="rtsp_url",
            field=models.TextField(null=True),
        ),
    ]
