# Generated by Django 5.1.3 on 2025-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0002_camera_rtsp_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="zone",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
