# Generated by Django 5.1.3 on 2025-01-19 18:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0003_camera_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="slug_name",
            field=models.CharField(max_length=255, null=False, blank=False),
        ),
    ]
