# Generated by Django 5.1.3 on 2025-01-20 04:47

from django.db import migrations, models


def create_default_camera_setting(apps, schema_editor):
    CameraSetting = apps.get_model("camera", "CameraSetting")
    CameraSetting.objects.create()


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0004_camera_slug_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enable_parcel_detect", models.BooleanField(default=False)),
                ("enable_face_recognition", models.BooleanField(default=False)),
                ("license_vehicle_recognition", models.BooleanField(default=False)),
                ("activate_sounds_detection", models.BooleanField(default=False)),
                ("footage_retention_period", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_default_camera_setting),
    ]
