# Generated by Django 5.1.3 on 2025-01-22 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0005_camerasetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasetting",
            name="loitering_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loitering_camera_setting",
                to="camera.camera",
            ),
        ),
        migrations.AddField(
            model_name="camerasetting",
            name="loitering_recognition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camerasetting",
            name="parcel_detect_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcel_detect_camera_setting",
                to="camera.camera",
            ),
        ),
    ]
