# Generated by Django 5.1.3 on 2025-02-06 09:28
import json

from django.db import migrations, models


def create_camera_organization_default_user(apps, schema_editor):
    with open("organization.json", "r") as file:
        data_dict = json.load(file)
    CameraOrganization = apps.get_model("camera", "CameraOrganization")
    organization_list = [CameraOrganization(**item) for item in data_dict]
    CameraOrganization.objects.bulk_create(organization_list)


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0006_camerasetting_loitering_camera_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mac_address_prefix", models.CharField(max_length=256, null=True)),
                ("organization_name", models.CharField(max_length=256, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_camera_organization_default_user),
    ]
