# Generated by Django 5.1.3 on 2025-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0007_cameraorganization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camerasetting",
            name="enable_face_recognition",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="camerasetting",
            name="license_vehicle_recognition",
            field=models.BooleanField(default=True),
        ),
    ]
