# Generated by Django 5.1.3 on 2025-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0008_alter_camerasetting_enable_face_recognition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
