# Generated by Django 5.1.3 on 2025-04-14 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0009_alter_camera_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camerasetting",
            name="loitering_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loitering_camera_setting",
                to="camera.camera",
            ),
        ),
        migrations.AlterField(
            model_name="camerasetting",
            name="parcel_detect_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parcel_detect_camera_setting",
                to="camera.camera",
            ),
        ),
    ]
