# Generated by Django 5.1.3 on 2025-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0010_alter_camerasetting_loitering_camera_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="is_audio",
            field=models.BooleanField(default=False),
        ),
    ]
