# Generated by Django 5.1.3 on 2025-12-08 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0012_camerasettingzone"),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasettingzone",
            name="objects_detect",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("person", "Person"), ("car", "Car")], max_length=20
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
