# Generated by Django 5.1.3 on 2025-12-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0013_camerasettingzone_objects_detect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camerasetting",
            name="loitering_camera",
        ),
        migrations.RemoveField(
            model_name="camerasetting",
            name="parcel_detect_camera",
        ),
        migrations.RemoveConstraint(
            model_name="camerasettingzone",
            name="unique_zone_per_camera",
        ),
        migrations.RemoveField(
            model_name="camerasettingzone",
            name="camera",
        ),
        migrations.AddField(
            model_name="camera",
            name="activate_sounds_detection",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="detect_zone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="enable_face_recognition",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="enable_parcel_detect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="footage_retention_period",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="license_vehicle_recognition",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="loitering_recognition",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="camera",
            name="slug_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name="CameraSetting",
        ),
    ]
