# Generated by Django 5.1.3 on 2025-12-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0014_remove_camerasetting_loitering_camera_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasettingzone",
            name="camera",
            field=models.ForeignKey(
                db_column="camera_slug",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camera_setting_zone",
                to="camera.camera",
                to_field="slug_name",
            ),
        ),
    ]
