# Generated by Django 5.1.3 on 2025-12-18 02:20

import django.db.models.deletion
from django.db import migrations, models


def create_default_camera_setting(apps, schema_editor):
    CameraSetting = apps.get_model("camera", "CameraSetting")
    CameraSetting.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0015_camerasettingzone_camera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="activate_sounds_detection",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="enable_face_recognition",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="enable_parcel_detect",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="footage_retention_period",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="license_vehicle_recognition",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="loitering_recognition",
        ),
        migrations.CreateModel(
            name="CameraSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enable_parcel_detect", models.BooleanField(default=False)),
                ("enable_face_recognition", models.BooleanField(default=True)),
                ("loitering_recognition", models.BooleanField(default=False)),
                ("license_vehicle_recognition", models.BooleanField(default=True)),
                ("activate_sounds_detection", models.BooleanField(default=False)),
                ("footage_retention_period", models.BooleanField(default=False)),
                (
                    "loitering_camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loitering_camera_setting",
                        to="camera.camera",
                    ),
                ),
                (
                    "parcel_detect_camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcel_detect_camera_setting",
                        to="camera.camera",
                    ),
                ),
                (
                    "vehicle_recognition_camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_recognition_camera_setting",
                        to="camera.camera",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_default_camera_setting),
    ]
