# Generated by Django 5.1.3 on 2025-12-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0016_remove_camera_activate_sounds_detection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="ring_device_id",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
