# Generated by Django 5.1.3 on 2026-02-03 09:01

from django.db import migrations, models


def set_camerasetting_defaults_false(apps, schema_editor):
    CameraSetting = apps.get_model("camera", "CameraSetting")
    CameraSetting.objects.all().update(
        loitering_recognition=False,
        license_vehicle_recognition=False,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0017_camera_ring_device_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camerasetting",
            name="enable_face_recognition",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="camerasetting",
            name="license_vehicle_recognition",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_camerasetting_defaults_false,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
