# Generated by Django 5.1.3 on 2026-04-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0018_alter_camerasetting_enable_face_recognition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="sub_rtsp_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="camera",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
