# Generated by Django 5.1.3 on 2025-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MerossCloudAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloud_region",
                    models.CharField(
                        choices=[("ap", "Ap"), ("eu", "Eu"), ("us", "Us")],
                        default=None,
                        max_length=256,
                        null=True,
                    ),
                ),
                ("email", models.CharField(default="", max_length=256, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MerossDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=256)),
                ("hass_entry_id", models.CharField(default="", max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
