# Generated by Django 5.1.3 on 2025-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meross", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merosscloudaccount",
            name="hass_entry_id",
            field=models.CharField(default="", max_length=256),
        ),
    ]
