# Generated by Django 5.1.3 on 2025-01-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(default="", max_length=256)),
                ("owner_name", models.CharField(default="", max_length=256)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            (None, "None"),
                            ("FAMILY", "FAMILY Vehicle"),
                            ("FRIEND", "Ring Vehicle"),
                        ],
                        default=None,
                        max_length=256,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("license_plate", "owner_name"),
                        name="unique_owner_license_plate",
                    )
                ],
            },
        ),
    ]
