# Generated by Django 5.1.3 on 2025-02-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image_url",
            field=models.TextField(null=True),
        ),
    ]
