# Generated by Django 5.1.3 on 2024-12-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=256)),
                ("camera", models.CharField(max_length=256)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("thumbnail", models.CharField(max_length=256)),
                ("sub_label", models.CharField(max_length=256)),
                ("snapshot_path", models.CharField(max_length=256)),
                ("video_path", models.CharField(max_length=256)),
                ("loitering", models.CharField(max_length=256)),
                ("additional_info", models.CharField(max_length=256)),
                ("face_detection_score", models.CharField(max_length=256)),
                ("parcel_status", models.CharField(max_length=256)),
            ],
        ),
    ]
