# Generated by Django 5.1.3 on 2024-12-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="camera",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="face_detection_score",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="event",
            name="audio_path",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="event",
            name="camera_name",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="event",
            name="confidence_score",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="event",
            name="face_embeddings",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="event",
            name="is_ignore_suggested_face",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_updated_known_face",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="vehicle_status",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="additional_info",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="label",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="loitering",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="parcel_status",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="snapshot_path",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="sub_label",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="video_path",
            field=models.CharField(default="", max_length=256),
        ),
    ]
