# Generated by Django 5.1.3 on 2025-01-13 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_remove_event_camera_remove_event_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="label",
            field=models.CharField(
                choices=[
                    ("PERSON", "PERSON Event"),
                    ("CAR", "CAR Event"),
                    ("ANIMAL", "ANIMAL Event"),
                    ("AUDIO", "AUDIO Event"),
                    ("PARCEL", "PARCEL Event"),
                ],
                default="PERSON",
                max_length=16,
            ),
        ),
    ]
