# Generated by Django 5.1.3 on 2025-01-19 18:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_event_created_at_event_updated_at_alter_event_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="parcel_id",
            field=models.CharField(max_length=256, default=""),
        ),
    ]
