# Generated by Django 5.1.3 on 2025-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_add_parcel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
    ]
