# Generated by Django 5.1.3 on 2025-01-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_event_confidence_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="face_embeddings",
            field=models.TextField(null=True),
        ),
    ]
