# Generated by Django 5.1.3 on 2025-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_event_face_embeddings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.CharField(default="", max_length=256, unique=True),
        ),
    ]
