# Generated by Django 5.1.3 on 2025-02-06 12:19

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_vector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
