# Generated by Django 5.1.3 on 2025-03-06 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_event_embedding_event_end_time_event_start_time"),
        ("facial", "0003_facial_is_ignore_alter_facial_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_face",
                to="facial.facial",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="vehicle_plate",
            field=models.CharField(default="", max_length=256),
        ),
    ]
