# Generated by Django 5.1.3 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_event_person_event_vehicle_plate"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["label"], name="event_label_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_time"], name="event_start_time_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["end_time"], name="event_end_time_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_at"], name="event_created_at_idx"),
        ),
    ]
