# Generated by Django 5.1.3 on 2026-02-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_event_add_performance_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="event_event_label_79334f_idx",
            old_name="event_label_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="event_event_start_t_f57654_idx",
            old_name="event_start_time_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="event_event_end_tim_77b5bd_idx",
            old_name="event_end_time_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="event_event_created_105efb_idx",
            old_name="event_created_at_idx",
        ),
    ]
