# Generated by Django 5.1.3 on 2025-02-10 06:56
import json
import os

import django.db.models.deletion
from django.db import migrations, models


def get_data_json():
    directory = "./manufacturer/data"
    json_files = sorted(f for f in os.listdir(directory) if f.endswith(".json"))
    data_list = []
    for file in json_files:
        file_path = os.path.join(directory, file)
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            data_list.append(data)
    return data_list


def create_camera_manufacturer_default(apps, schema_editor):
    data_json = get_data_json()
    CameraManufacturer = apps.get_model("manufacturer", "CameraManufacturer")
    manufacturer_objects = [
        CameraManufacturer(manufacturer_name=item.get("name")) for item in data_json
    ]

    CameraManufacturer.objects.bulk_create(manufacturer_objects)
    manufacturer_dict = dict(
        CameraManufacturer.objects.values_list("manufacturer_name", "id")
    )
    CameraModel = apps.get_model("manufacturer", "CameraModel")
    camera_model_objects = []
    for item in data_json:
        name = item["name"]
        if (
            name in manufacturer_dict
        ):  # Check if the name exists in bprint(' item["name"]',  name)

            id_value = manufacturer_dict[name]
            for model in item["models"]:
                model_with_id = (
                    model.copy()
                )  # Copy model to avoid modifying original data
                model_with_id["camera_manufacturer_id"] = id_value
                camera_model_objects.append(CameraModel(**model_with_id))
    CameraModel.objects.bulk_create(camera_model_objects)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer_name", models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CameraModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=256, null=True)),
                ("type", models.CharField(max_length=256, null=True)),
                ("protocol", models.CharField(max_length=256, null=True)),
                ("url", models.CharField(max_length=256, null=True)),
                (
                    "camera_manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camera_model_camera_manufacturer",
                        to="manufacturer.cameramanufacturer",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_camera_manufacturer_default),
    ]
