# Generated by Django 5.1.3 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cameramanufacturer",
            index=models.Index(
                fields=["manufacturer_name"], name="manufacturer_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cameramodel",
            index=models.Index(fields=["model"], name="camera_model_model_idx"),
        ),
        migrations.AddIndex(
            model_name="cameramodel",
            index=models.Index(fields=["type"], name="camera_model_type_idx"),
        ),
        migrations.AddIndex(
            model_name="cameramodel",
            index=models.Index(
                fields=["camera_manufacturer", "model"],
                name="cam_model_mfr_model_idx",
            ),
        ),
    ]
