# Generated by Django 5.1.3 on 2026-02-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cameramanufacturer",
            new_name="manufacture_manufac_b1fd7e_idx",
            old_name="manufacturer_name_idx",
        ),
        migrations.RenameIndex(
            model_name="cameramodel",
            new_name="manufacture_model_48d3b1_idx",
            old_name="camera_model_model_idx",
        ),
        migrations.RenameIndex(
            model_name="cameramodel",
            new_name="manufacture_type_65e4b0_idx",
            old_name="camera_model_type_idx",
        ),
        migrations.RenameIndex(
            model_name="cameramodel",
            new_name="manufacture_camera__2cb24d_idx",
            old_name="cam_model_mfr_model_idx",
        ),
    ]
