# Generated by Django 5.1.3 on 2024-12-02 09:55

import os

from django.contrib.auth import get_user_model
from django.db import migrations


def create_default_user(apps, schema_editor):
    User = get_user_model()

    User.objects.create_user(
        username="hub", password=os.getenv("HUB_SECRET", "EXAMPLE PASSWORD")
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(create_default_user)]
