# Generated by Django 5.1.3 on 2025-02-12 02:16

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("face_training", "0002_vector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetraining",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=512, null=True
            ),
        ),
    ]
