# Generated by Django 5.1.3 on 2025-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_training", "0003_facetraining_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetraining",
            name="is_ignore",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facetraining",
            name="person_name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
