# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_training", "0004_facetraining_is_ignore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetraining",
            name="quality_score",
            field=models.FloatField(default=0.0, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="facetraining",
            name="augmentation_type",
            field=models.CharField(max_length=64, null=True, blank=True),
        ),
    ]
