# Generated by Django 5.1.3 on 2025-01-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlarmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("night", "Night"),
                            ("away", "Away"),
                        ],
                        default="travel",
                        max_length=32,
                    ),
                ),
                ("auto_active_schedule", models.BooleanField(default=False)),
                ("auto_active_schedule_start", models.IntegerField(default=0)),
                ("auto_active_schedule_end", models.IntegerField(default=0)),
                (
                    "sound",
                    models.CharField(
                        choices=[
                            ("alarm", "Alarm"),
                            ("party", "Party"),
                            ("movie", "Movie"),
                            ("dog barking", "Dog Barking"),
                        ],
                        default="alarm",
                        max_length=32,
                    ),
                ),
                ("conditions", models.JSONField(default=list)),
                ("volume", models.IntegerField(default=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
