# Generated by Django 5.1.3 on 2025-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmsettings",
            name="auto_active_schedule_end",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="alarmsettings",
            name="auto_active_schedule_start",
            field=models.BigIntegerField(default=0),
        ),
    ]
