# Generated by Django 5.1.3 on 2025-01-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_alter_alarmsettings_auto_active_schedule_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmsettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("travel", "Travel"),
                    ("night", "Night"),
                    ("away", "Away"),
                ],
                default="travel",
                max_length=32,
            ),
        ),
    ]
