# Generated by Django 5.1.3 on 2025-01-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_alter_alarmsettings_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmsettings",
            name="speakers",
            field=models.BooleanField(default=False),
        ),
    ]
