# Generated by Django 5.1.3 on 2025-04-08 02:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_alarmsettings_speakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmsettings",
            name="auto_active_schedule_repeat",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Monday", "Monday"),
                        ("Tuesday", "Tuesday"),
                        ("Wednesday", "Wednesday"),
                        ("Thursday", "Thursday"),
                        ("Friday", "Friday"),
                        ("Saturday", "Saturday"),
                        ("Sunday", "Sunday"),
                    ],
                    default=None,
                    max_length=32,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="auto_trigger_loiter_detection_alarm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="auto_trigger_manual_alarm_prompt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="auto_trigger_trusted_face_disarm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="repeat_type",
            field=models.CharField(
                choices=[
                    ("every_day", "Every Day"),
                    ("custom", "Custom"),
                    ("never", "Never"),
                ],
                default="never",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="run_duration_sound",
            field=models.IntegerField(default=1),
        ),
    ]
