# Generated by Django 5.1.3 on 2025-04-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_alarmsettings_auto_active_schedule_repeat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmsettings",
            name="sound",
            field=models.CharField(
                choices=[
                    ("alarm", "Alarm"),
                    ("party", "Party"),
                    ("movie", "Movie"),
                    ("dog_barking", "Dog Barking"),
                ],
                default="alarm",
                max_length=32,
            ),
        ),
    ]
