# Generated by Django 5.1.3 on 2025-04-21 03:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0006_alter_alarmsettings_sound"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmsettings",
            name="auto_active_schedule_repeat",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Monday", "Monday"),
                        ("Tuesday", "Tuesday"),
                        ("Wednesday", "Wednesday"),
                        ("Thursday", "Thursday"),
                        ("Friday", "Friday"),
                        ("Saturday", "Saturday"),
                        ("Sunday", "Sunday"),
                    ],
                    default=None,
                    max_length=32,
                    null=True,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
