# Generated by Django 5.1.3 on 2025-07-24 03:27

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0007_alter_alarmsettings_auto_active_schedule_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmsettings",
            name="auto_trigger_detected_sounds",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="auto_trigger_detected_sounds_value",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("all_sound", "All Sound"),
                        ("dangerous", "Dangerous"),
                        ("noteworthy", "Noteworthy"),
                    ],
                    default="all_sound",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="delay",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="unusual_sound_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="alarmsettings",
            name="run_duration_sound",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="alarmsettings",
            name="volume",
            field=models.IntegerField(
                default=50, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
