# Generated by Django 5.1.3 on 2026-01-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarm", "0005_remove_alarmdevice_unusual_sound_enabled_and_more"),
        ("automation", "0008_alarmsettings_auto_trigger_detected_sounds_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_active_schedule",
            new_name="known_face_disarm",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_trigger_detected_sounds",
            new_name="live_activity_prompt",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_trigger_loiter_detection_alarm",
            new_name="loitering_activate",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_trigger_manual_alarm_prompt",
            new_name="parcel_theft_activate",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_trigger_trusted_face_disarm",
            new_name="schedule",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_active_schedule_end",
            new_name="schedule_end",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_active_schedule_repeat",
            new_name="schedule_repeat",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="auto_active_schedule_start",
            new_name="schedule_start",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="run_duration_sound",
            new_name="sound_duration",
        ),
        migrations.RenameField(
            model_name="alarmsettings",
            old_name="unusual_sound_enabled",
            new_name="unusual_sound_activate",
        ),
        migrations.RemoveField(
            model_name="alarmsettings",
            name="auto_trigger_detected_sounds_value",
        ),
        migrations.RemoveField(
            model_name="alarmsettings",
            name="conditions",
        ),
        migrations.RemoveField(
            model_name="alarmsettings",
            name="speakers",
        ),
        migrations.AddField(
            model_name="alarmsettings",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_settings_device",
                to="alarm.alarmdevice",
            ),
        ),
        migrations.AlterField(
            model_name="alarmsettings",
            name="sound",
            field=models.CharField(
                choices=[
                    ("alarm", "Alarm"),
                    ("people_home", "People at Home"),
                    ("running_appliances", "Running Appliances"),
                    ("barking_dogs", "Barking Dogs"),
                ],
                default="alarm",
                max_length=32,
            ),
        ),
    ]
