# Generated by Django 5.1.3 on 2026-03-19 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_rename_auto_active_schedule_alarmsettings_known_face_disarm_and_more'),
        ('external_device', '0002_externaldevice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmsettings',
            name='entry_door_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='entry_door_all_sensors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='entry_door_exit_delay_seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='entry_sensors',
            field=models.ManyToManyField(blank=True, related_name='alarm_settings_entry_sensors', to='external_device.externaldevice'),
        ),
    ]
