# Generated by Django 5.1.3 on 2025-05-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("camera", "0010_alter_camerasetting_loitering_camera_and_more"),
        ("meross", "0002_merosscloudaccount_hass_entry_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarageDoorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_open", models.BooleanField(default=False)),
                ("auto_close", models.BooleanField(default=False)),
                ("auto_close_delay", models.IntegerField(default=1)),
                ("auto_open_on_owner", models.BooleanField(default=False)),
                ("card_on_owner", models.BooleanField(default=False)),
                ("card_on_unknown", models.BooleanField(default=False)),
                (
                    "camera",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camera_auto_garage_setting",
                        to="camera.camera",
                    ),
                ),
                (
                    "garage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_garage_setting",
                        to="meross.merossdevice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
