"""
Django settings for hub_controller project.

Generated by 'django-admin startproject' using Django 3.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "authentication",
    "event",
    "bounding_box",
    "camera",
    "ring",
    "file",
    "facial",
    "vehicle",
    "loitering",
    "parcel_detect",
    "django_filters",
    "alarm",
    "network",
    "automation",
    "hub_operations",
    "pgvector",
    "manufacturer",
    "face_training",
    "suggested_facial",
    "meross",
    "logbook",
    "automation_garage",
    "django_celery_beat",
    "cloudflare_turn",
    "external_device",
    "gdrive_backup",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hub_controller.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hub_controller.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# Read timezone from the host system. The hub's /etc/timezone is set during
# onboarding (from the user's phone locale) and NTP keeps the clock accurate.
# All services (Django, Celery, PostgreSQL, Docker containers) must agree on
# the same timezone to prevent double-conversion bugs in django_celery_beat.
def _read_system_timezone():
    tz = os.environ.get("TZ")
    if tz and tz != "UTC":
        return tz
    try:
        with open("/etc/timezone") as f:
            return f.read().strip()
    except (OSError, IOError):
        return "UTC"

TIME_ZONE = _read_system_timezone()

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATIC_URL = "/static/"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Docs
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"},
        "Basic": {"type": "basic", "name": "HubCredentials"},
    }
}

# Celery Configuration Options
# All times stored and compared in UTC (USE_TZ=True + CELERY_ENABLE_UTC=True).
# TIME_ZONE above is local for display only. PostgreSQL must also run in UTC.
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TIMEZONE = "UTC"

CELERY_TASK_QUEUES = (
    Queue("camera_queue", routing_key="camera.#"),
    Queue("loitering_queue", routing_key="loitering.#"),
    Queue("parcel_detect_queue", routing_key="parcel_detect.#"),
    Queue("facial_queue", routing_key="facial_queue.#"),
    Queue("hub_operations_queue", routing_key="hub_operations.#"),
    Queue("automation_queue", routing_key="automation.#"),
)

CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_DEFAULT_ROUTING_KEY = "default"

CELERY_TASK_ROUTES = {
    "camera.tasks.update_camera_config": {
        "queue": "camera_queue",
        "routing_key": "camera.task",
    },
    "camera.tasks.camera_setting_config": {
        "queue": "camera_queue",
        "routing_key": "camera.task",
    },
    "camera.tasks.update_frigate_config": {
        "queue": "camera_queue",
        "routing_key": "camera.task",
    },
    "camera.tasks.heal_ai_constants": {
        "queue": "camera_queue",
        "routing_key": "camera.task",
    },
    "camera.tasks.restart_ring_safe": {
        "queue": "ring_safe_queue",
        "routing_key": "camera.task",
    },
    "ring.tasks.set_ring_token": {
        "queue": "camera_queue",
        "routing_key": "camera.task",
    },
    "loitering.tasks.update_loitering_config": {
        "queue": "loitering_queue",
        "routing_key": "loitering.task",
    },
    "parcel_detect.tasks.update_parcel_detect_config": {
        "queue": "parcel_detect_queue",
        "routing_key": "parcel_detect.task",
    },
    "facial.tasks.create_facial_config": {
        "queue": "facial_queue",
        "routing_key": "facial.task",
    },
    "hub_operations.tasks.hub_reset_task": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.task",
    },
    "hub_operations.tasks.hub_auto_restart_cloudflare_token": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.task",
    },
    "automation.tasks.automation_alarm_loitering_config": {
        "queue": "loitering_queue",
        "routing_key": "loitering.task",
    },
    "automation.tasks.create_manual_alarm_automations": {
        "queue": "automation_queue",
        "routing_key": "automation.task",
    },
    "automation.tasks.retry_esphome_later": {
        "queue": "automation_queue",
        "routing_key": "automation.fallback",
    },
    "alarm.tasks.alarm_unusual_sound_config": {
        "queue": "automation_queue",
        "routing_key": "alarm.task",
    },
    "alarm.tasks.alarm_voice_ai_config": {
        "queue": "automation_queue",
        "routing_key": "alarm.task",
    },
    "alarm.tasks.monitor_alarm_ips": {
        "queue": "automation_queue",
        "routing_key": "alarm.task",
    },
    "camera.tasks.monitor_camera_ips": {
        "queue": "camera_queue",
        "routing_key": "camera.task",
    },
    "gdrive_backup.tasks.run_backup": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.gdrive",
    },
    "gdrive_backup.tasks.run_restore": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.gdrive",
    },
    "gdrive_backup.tasks.run_scheduled_backups": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.gdrive",
    },
    "gdrive_backup.tasks.check_gdrive_space": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.gdrive",
    },
    "event.tasks.scan_broken_video_paths": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.task",
    },
    "event.tasks.ensure_local_clip_task": {
        "queue": "hub_operations_queue",
        "routing_key": "hub_operations.task",
    },
}

# Camera thumbnail cache — proactively refreshed by camera.tasks.capture_camera_snapshots
# every 5 minutes, read by camera.views.CameraSnapshotProxyView. Both must point at the
# same dir; previously they diverged (task wrote to BASE_DIR/media/thumbnails, view read
# from a hardcoded literal that didn't match) and the cache was effectively unused.
CAMERA_THUMBNAILS_DIR = os.environ.get(
    "CAMERA_THUMBNAILS_DIR",
    "/root/jupyter-hub-controller/media/thumbnails",
)


# Celery Beat Schedule — periodic tasks
CELERY_BEAT_SCHEDULE = {
    "rotate-turn-credentials-every-12h": {
        "task": "hub_operations.tasks.hub_auto_restart_cloudflare_token",
        "schedule": 12 * 60 * 60,  # every 12 hours (seconds)
    },
    "monitor-camera-ips-every-5m": {
        "task": "camera.tasks.monitor_camera_ips",
        "schedule": 5 * 60,  # every 5 minutes (seconds)
    },
    # Auto-heal AI bind-mounted constants.py files. See
    # camera/tasks.py:heal_ai_constants for the full design rationale and
    # offboarding/onboarding semantics.
    "heal-ai-constants-every-60s": {
        "task": "camera.tasks.heal_ai_constants",
        "schedule": int(os.getenv("AI_HEALER_INTERVAL_S", "60")),
    },
    "gdrive-scheduled-backups-every-5m": {
        "task": "gdrive_backup.tasks.run_scheduled_backups",
        "schedule": 5 * 60,
    },
    "gdrive-space-check-every-6h": {
        "task": "gdrive_backup.tasks.check_gdrive_space",
        "schedule": 6 * 60 * 60,
    },
    # Proactive snapshot cache — every 5 min refresh /media/thumbnails/<slug>.jpg
    # for every enabled camera. Endpoints serving the cached file (legacy
    # /snapshot, dashboard tiles, WebRTCPlayer poster) become near-instant
    # (~10ms file read). The wizard's /rtsp-snapshot bypasses this and goes
    # live for fresh framing when the user is actively setting up calibration.
    "capture-camera-snapshots-every-5m": {
        "task": "camera.tasks.capture_camera_snapshots",
        "schedule": 5 * 60,
    },
    "scan-broken-video-paths-every-30s": {
        "task": "event.tasks.scan_broken_video_paths",
        "schedule": 30,
    },
    "monitor-alarm-ips-every-5m": {
        "task": "alarm.tasks.monitor_alarm_ips",
        "schedule": 5 * 60,
    },
}
